#### 7. Reshape a 1D array of size 12 into a 3×4 matrix.

In [1]:
import numpy as np

In [2]:
array = np.random.randint(1, 100, size=[1, 12])
print(array)

[[35 29 66 69 87 94 68  6 26 26 21 41]]


In [3]:
new_matrix = np.reshape(array, (3, 4))
print(new_matrix)

[[35 29 66 69]
 [87 94 68  6]
 [26 26 21 41]]
