##### 10. Perform element-wise addition and multiplication on two arrays.

In [13]:
import numpy as np

In [14]:
np.random.seed(24)

In [15]:
matrix = np.random.randint(1, 100, size=[2, 3])
vector = np.random.randint(1, 100, size=[1, 3])

In [16]:
print(matrix)
print(vector)

[[35  4 65]
 [88 18 18]]
[[ 2 80  5]]


In [17]:
print(matrix + vector)
print(matrix * vector)

[[37 84 70]
 [90 98 23]]
[[  70  320  325]
 [ 176 1440   90]]
