# Practice 11

In [1]:
import numpy as np

### Find row-wise and column-wise sums of a 2D array.

In [2]:
np.random.seed(24)

In [3]:
array = np.random.randint(0, 100, size=[2, 3])
print(array)

[[34  3 64]
 [87 17 17]]


In [4]:
sum_column = np.sum(array, axis=0)
print(sum_column)

[121  20  81]


In [5]:
sum_row = np.sum(array, axis=1)
print(sum_row)

[101 121]
