# Practice 1

Importing numpy package

In [19]:
import numpy as np

### Converting list to array

In [20]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### creating matrices zeros

In [21]:
zero = np.zeros((2,3))
print(zero)


[[0. 0. 0.]
 [0. 0. 0.]]


### creatng matrices one

In [22]:
one = np.ones((2,3))
print(one)


[[1. 1. 1.]
 [1. 1. 1.]]


### creating matrices with range

np.arrange(start, end, interval/gap)

In [ ]:
in_range = np.arange(1, 10, 2)
print(in_range)

[1 3 5 7 9]


### linspace array

gives an range between 2 number with given interval/gap 
np.linspace(start, end, interval/gap)

In [24]:
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]
