# Practice 2

In [4]:
import numpy as np

#### Creating an array

In [5]:
array = np.array((1, 2, 3, 4, 5, 6))
print(array)

[1 2 3 4 5 6]


#### reshapes a 1d array to 2d array

In [6]:
new_arr = array.reshape((2,3))
print(new_arr)


[[1 2 3]
 [4 5 6]]


#### diff dimensions

In [7]:
expanded = array[:, np.newaxis]
print(expanded)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
