# Practice 3

In [7]:
import numpy as np

### Mathematical operations on array

#### Creating basic arrays

In [8]:
arr = np.array((1, 2, 3, 4, 5, 6, 10))

arr2 = np.array((2, 1, 5, 6, 7, 8, 9))

#### Addition

In [9]:
print(arr + arr2)

[ 3  3  8 10 12 14 19]


#### Multiplication

In [10]:
print(arr * arr2)

[ 2  2 15 24 35 48 90]


#### Subtraction

In [11]:
print(arr - arr2)

[-1  1 -2 -2 -2 -2  1]


#### Division

In [12]:
print(arr / arr2)

[0.5        2.         0.6        0.66666667 0.71428571 0.75
 1.11111111]


### Creating another array with square values

In [13]:
x = np.array((4, 9, 16, 25))

#### Square root

In [14]:
print(np.sqrt(x))

[2. 3. 4. 5.]


#### sum of all elements

In [15]:
print(np.sum(np.sqrt(x)))

14.0


#### mean of the array

In [16]:
print(np.mean(x))

13.5


#### max of the array

In [17]:
print(np.max(x))

25


#### min of the array

In [18]:
print(np.min(x))

4
