# Practice 4

In [1]:
import numpy as np

#### Creating an array

In [2]:
arr = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9))

##### indexing - array always start from 0

In [3]:
print(arr[5])
print(arr[-1]) # negative indexing

6
9


#### slicing an array

In [4]:
print(arr[3:8])
print(arr[::-1]) # negative slicing

[4 5 6 7 8]
[9 8 7 6 5 4 3 2 1]


#### reshaping

In [5]:
reshaped = arr.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
