# Practice 5

In [1]:
import numpy as np

#### Creating an array

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#### array transpose

In [3]:
transpose = matrix.T

In [4]:
print(matrix)
print(transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### Creating another matrix

In [5]:
another_matix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(another_matix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Adding the transposed array

In [6]:
print(matrix + another_matix)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
