# Practice 7

In [4]:
import numpy as np

##### broadcasting : it allows numpy to perform arithmetic operations of diff shapes, smaller array matches the dimension of the larger array

<p> Creating an array </p>

In [5]:
arr = np.array([[1, 2, 3]])
print(arr)

[[1 2 3]]


<p>Adding 10 to an array</p>

In [6]:
print(arr + 10)

[[11 12 13]]


#### Creating an 2d array

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


#### Creating an vector

In [8]:
vector = np.array([9, 6 , 8])
print(vector)

[9 6 8]


#### Adding an 1d array and 2d array

In [9]:
print(matrix + vector)

[[10  8 11]
 [13 11 14]]
