# Practice 9

In [1]:
import numpy as np

#### Boolean indexing
<p>boolean indexing means creating a boolean array using conditions and use that boolean array to pick only those element where the value is true</p>

#### Creating an 2d array

In [2]:
arr = np.array([[1, 2, 3], [5, 7, 9]])
print(arr)

[[1 2 3]
 [5 7 9]]


#### Filtering array with even elements

In [3]:
evens = arr[arr % 2 == 0] 
print(evens)

[2]


<p>More filtering way</p>

In [4]:
arr[arr > 3] = 0
print("Modified array : ", arr)

Modified array :  [[1 2 3]
 [0 0 0]]
