# Practice 10

In [16]:
import numpy as np

#### Generating a random number array

In [17]:
random_array = np.random.rand(3, 4)
print(random_array)

[[0.29443381 0.05285462 0.31748822 0.98394927]
 [0.50901966 0.7871809  0.47405119 0.61872193]
 [0.27462813 0.55996471 0.02030796 0.6645504 ]]


#### Generating real random number

In [18]:
random_integers = np.random.randint(0, 10, size=[2, 3])
print(random_integers)

[[3 0 1]
 [1 7 6]]


#### Seeding

In [19]:
np.random.seed(24)

In [20]:
random_array = np.random.randint(3, 15, size=[2, 3])
print(random_array)

[[ 5  6  3]
 [10  4  4]]
