# Practice 11

In [1]:
import numpy as np

#### Creating a 2d array and a vector

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [3]:
vector = np.array([1,4,8])
print(vector)

[1 4 8]


#### Addition

In [4]:
print(matrix + vector)

[[ 2  6 11]
 [ 5  9 14]]


#### Multiplication

In [5]:
print(matrix * vector)

[[ 1  8 24]
 [ 4 20 48]]
