# Practice 12

In [3]:
import numpy as np

#### Generating a random matrix

In [4]:
matrix = np.random.randint(1, 51, size=[3,4])
print(matrix)

[[30 25  6 12]
 [31 45 26  4]
 [48 14  7 27]]


#### filtering data set

In [5]:
matrix[matrix > 25] = 0
print("\n", matrix)


 [[ 0 25  6 12]
 [ 0  0  0  4]
 [ 0 14  7  0]]


#### calculate summary stat

In [6]:
print("Sum : ", np.sum(matrix))
print("Mean : ", np.mean(matrix))
print("Standard deviation : ", np.std(matrix))

Sum :  68
Mean :  5.666666666666667
Standard deviation :  7.5314156851300025
