# Practice 13

In [1]:
import numpy as np

#### Seeding value

In [2]:
np.random.seed(24)

#### generating a array with random numbers

In [3]:
matrix = np.random.randint(1, 100, size=[5, 5])
print(matrix)

[[35  4 65 88 18]
 [18  2 80  5 83]
 [12 16 74 19  8]
 [26 36 96 29  1]
 [13 96 34  2 61]]


#### printing stats column wise

In [4]:
column_mean = np.mean(matrix, axis=0)
column_std = np.std(matrix, axis=0)
column_sum = np.sum(matrix, axis=0)

In [5]:
print("mean of the column : ",column_mean)
print("sum of the column : ",column_sum)
print("std of the column : ",column_std)

mean of the column :  [20.8 30.8 69.8 28.6 34.2]
sum of the column :  [104 154 349 143 171]
std of the column :  [ 8.65794433 34.7701021  20.55626425 31.25763907 32.09610568]


#### row wise stats

In [6]:
rows_mean = np.mean(matrix, axis=1)
rows_sum = np.sum(matrix, axis=1)
rows_std = np.std(matrix, axis=1)

In [7]:
print("mean of the rows : ", rows_mean)
print("sum of the rows : ", rows_sum)
print("std of the rows : ", rows_std)

mean of the rows :  [42.  37.6 25.8 37.6 41.2]
sum of the rows :  [210 188 129 188 206]
std of the rows :  [30.70504844 36.25796464 24.38360105 31.49984127 33.99647041]
